steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/meditation-431811/my-flask-app:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/meditation-431811/my-flask-app:latest']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'my-flask-app',
      '--image', 'gcr.io/meditation-431811/my-flask-app:latest',
      '--region', 'australia-southeast1',
      '--platform', 'managed',
      #'--allow-unauthenticated'  # Optional: Allow public access#
    ]
images:
  - 'gcr.io/meditation-431811/my-flask-app:latest'
options:
  logging: CLOUD_LOGGING_ONLY